### ISSUE TITLE
Modelname warning when need types have "-"

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-modeling#16]
The [modeling guidelines](https://sphinx-modeling.useblocks.com/modeling.html#model-names) talks about the model names to be used. I have need types with "-" in the need type names. I could not create a matching model name for it.

For example, 

need type: `req-sw`

Model definition:
```
class ReqSw(BaseModelNeeds):
    id: str
    type: Literal["req-sw"]
```
Tested model names: `ReqSw`, `Reqsw`

Results in:

`WARNING: Model validation: no model defined for need type 'req-sw'`

**Comment by twodrops** [comment]
@ubmarco Thanks for the real quick feedback :)

I have a stupid question.

```
class ReqSw(BaseModelNeeds):
    id: str
    type: Literal["req-sw"]
```

There is an implict mapping between the classname (`ReqSw`) and needtype name (`req-sw`) already here. Why can't this be used?

If this cannot be used, can we combine both your suggestions to have a default behavior of stripping Python identifiers and override the behavior (if needed) with a mapping dictionary?

**Comment by ubmarco** [comment]
[Here](https://github.com/useblocks/sphinx-modeling/blob/a91e63772e67f1938d3cb71d0b2323b1107b6701/sphinx_modeling/modeling/main.py#L105) you can see what is done.
I just use `need["type"].title()`. For `req-sw` this leads to `Req-Sw` which is not a valid class name. Stripping off non-identifier characters would lead to `Reqsw`. This implicit logic must currently be known by the end user.
Ideally there is just one way of doing things. My proposal is to change the parameter [modeling_models](https://sphinx-modeling.useblocks.com/configuration.html#modeling-models) to be a dictionary:
```
class ReqSw(BaseModelNeeds):
  id: str

modeling_models = {
    'req-sw': ReqSw
}
```
For 2 reasons:

- avoid implicit logic & the user is in control of the mapping
- ability to auto-generate the `type` field (`type: Literal["req-sw"]`) in future as this is the primary need identifier which *should* have a constraint.

**Comment by twodrops** [comment]
My question was more in another direction:

```
class ReqSw(BaseModelNeeds):
    id: str
    type: Literal["req-sw"]
```

The class is called `ReqSw` already and the literal says `req-sw`. What's the purpose of the classname if we need yet another mapping? 

```
class ReqSw(BaseModelNeeds):
  id: str

modeling_models = {
    'req-sw': ReqSw
}
```

With this I have `ReqSw` duplicated twice.

I didn't look into the technical details of how the matching is done currently, but from the user-perspeactive I have specified the mapping already using the classname and a literal. Why do I need another default mapping or a dictionary based mapping?

**Comment by ubmarco** [comment]
I thought about this for a while. Some points to consider:

- Generally speaking, the current solution allows really everything. Pydantic does not know that sphinx-needs has a type field that is used to distinguish the various need 'classes' (as in class-object relation). And sphinx-modeling puts no constraints on what users define in their model. Users may want to use the `id` field or `type` or another field to validate a need or a linked/nested model. So having the `type` field in your above model is no requirement at all. Just add `"type"` to `modeling_remove_fields` and pydantic will not complain that the `type` field has no validation. The sample code and docs is just how I thought it makes sense.
- sphinx-modeling needs a clear way to know which model to use to validate a certain need. sphinx-modeling is based on the assumption that each model maps to a certain need type (which I think makes sense). The mapping knowledge can either be implicit (derived from class name) or explicit. If projects use `sw-req` and `swreq` as need types (we can discuss whether that's a smart idea), it might lead to the same class name and the implicit derivation will fail. In the explicit variant the class name would play no role at all, however information duplication would occur.
- [PEP8](https://peps.python.org/pep-0008/#class-names) expects class names to have CamelCase style

I will stick to the implicit variant but turn any given identifier to a valid CamelCase identifier.
This avoids duplication and leads to valid, compliant and human readable class names.

Here is my [PR](https://github.com/useblocks/sphinx-modeling/pull/19). It is already merged.
If you are happy with the solution, please close the issue.

**Comment by ubmarco** [comment]
@twodrops Any feedback on this? I plan to release a new version this week which includes this change.

**Comment by twodrops** [comment]
@ubmarco 

I went through the comments again and I guess I understand it better now :)

```
class ReqSw(BaseModelNeeds):
  id: str
  type: Literal["req-sw"]
```

This means `type` here does not do any model mapping between `ReqSw` and `req-sw`, but only tells Pydantic that it should validate the field `type`.

In that case, I would go with your mapping idea using a dictionary.

As a side comment, I find the model definitions in this way and having a dictionary for it, too verbose and more a pythonic thing. It somehow does not match the original need to have a self-contained model-definition language for Sphinx-Needs. I know that this is a consequence of using Python/PyDantic for model definition here and not related to your current implementation. I am wondering if it makes sense to hide these behind some kind of a [Fluent Interface](https://de.wikipedia.org/wiki/Fluent_Interface) so that the model definitions are easy from a user point of view and does not need much python knowledge. But that's a different topic.

**Comment by ubmarco** [comment]
Thanks for the feedback.

> This means type here does not do any model mapping between ReqSw and req-sw, but only tells Pydantic that it should validate the field type.

Correct.

> In that case, I would go with your mapping idea using a dictionary.

After working with the extension for a while now, I agree. There is a constraint here for an unambiguous need type to Pydantic class mapping, so making this explicit is the better solution.

> As a side comment, I find the model definitions in this way and having a dictionary for it, too verbose and more a pythonic thing.

I still feel Pydantic is the right tool as it
- produces good validation messages
- is easy enough for devs/engineers that understand Pydantic and some Python
- can model every constraint I can imagine

However, I also agree that some modeling is quite verbose. Especially now I am looking into circular link loops which are not supported by Pydantic, so the modeling needs to adapt here. It is perfectly possible to validate all links (and also foreign fields) and not run into recursion issue. See https://github.com/useblocks/sphinx-modeling/pull/25.
The new behavior also makes the modeling more explicit as less magic is happening behind the scenes.
It is, however, more verbose. I am still working on the docs for it.

Do you have a modeling language in mind that is easier than Pydantic but still precise and concise and can serve as a fluent interface to generate the Pydantic classes?

**Comment by ubmarco** [comment]
`modeling_models` dictionaries implemented in https://github.com/useblocks/sphinx-modeling/pull/26.
