### ISSUE TITLE
Update motivation with more compelling reasons

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-modeling#18]
The motivation listed at https://github.com/useblocks/sphinx-modeling#motivation reads:

>This is a problem for organizations that want to enforce well defined (UML) standards on objects. Especially when migrating parts of the requirements management system to Sphinx-Needs it is crucial to be consistent with existing solutions. Doing so enables technological interoperability.

I guess some more compelling reasons are:

- defining model constraints (typed links, multiplicity, allowed attributes, allowed values etc) as part of your model definition (and not as `need_warnings`). This leaves `need_warnings` with the load of doing only data relevant checks later. That is, reduce glue and duplication as much as possible.
- automatic visualization of typed model (the PlantUML solution which is planned)
- self contained need definitions which does not leave types, options, links, warnings scattered (the opposite of the current global definition, if someone wishes to keep it self-contained)
- user-documentation of meta-model (Way to automatically create readable textual doumentation on the types, its allowed values etc. Can be combined with additional docstring documentation as part of model definition if needed)
- possibility to use the typed model in external tools (VsCode Extension, Linter etc.)
- possibility to auto-generate [needs_ide_directive_snippets](https://sphinxcontrib-needs.readthedocs.io/en/latest/configuration.html#needs-ide-directive-snippets)

**Comment by ubmarco** [comment]
Thanks for the ideas, I added them.
